language: python
sudo: false
matrix:
    include:
        - python: 3.4
          dist: trusty
        - python: 3.5
          dist: trusty
        - python: 3.6
          dist: trusty
        - python: 3.7
          dist: xenial
          sudo: true
addons:
  apt:
    packages:
    - libmagickwand-dev
install:
- pip install -e .[tests]
- pip install pytest-cov coveralls
script:
- pytest -v --cov ugoira
- flake8 ugoira tests
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && coveralls || false'
notifications:
  irc:
    channels:
    - "irc.ozinger.org#item4"
    on_success: change
    on_failure: always
